EXPERIMENT:
  NAME: ""
  TAG: "dkd,vgg13,vgg8"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  SGD:
    MOMENTUM: 0.9
  SCHEDULE:
    MULTISTEP:
      STAGES: [150, 180, 210]
      RATE: 0.1
  WEIGHT_DECAY: 0.0005
  TYPE: "SGD"
DKD:
  BETA: 6.0
