EXPERIMENT:
  NAME: ""
  TAG: "ofd,res50,mobilenetv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "OFD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.05
  SGD:
    MOMENTUM: 0.9
  SCHEDULE:
    MULTISTEP:
      STAGES: [30, 60, 90]
      RATE: 0.1
  WEIGHT_DECAY: 0.0001
  TYPE: "SGD"
OFD:
  LOSS:
    FEAT_WEIGHT: 0.0001
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
