EXPERIMENT:
  NAME: ""
  TAG: "fitvit-baseline,clip-base,vit-tiny,weight-100.0"
  PROJECT: "CLIP_FitViT"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "FITVIT"
  TEACHER: "clip_base"
  STUDENT: "vit_tiny"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  SGD:
    MOMENTUM: 0.9
  SCHEDULE:
    MULTISTEP:
      STAGES: [30, 60, 90]
      RATE: 0.1
  WEIGHT_DECAY: 0.0001
  TYPE: "SGD"
FITNET:
  INPUT_SIZE: [224, 224]
  HINT_LAYER: 7
  LOSS:
    FEAT_WEIGHT: 100.0
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
AF:
  ENABLE: False
# FITNET:
#   HINT_LAYER: 8