EXPERIMENT:
  NAME: ""
  TAG: "pkt,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "PKT"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  SGD:
    MOMENTUM: 0.9
  SCHEDULE:
    MULTISTEP:
      STAGES: [150, 180, 210]
      RATE: 0.1
  WEIGHT_DECAY: 0.0005
  TYPE: "SGD"
